- name: Update and upgrade apt packages
  hosts: all
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 
  - name: print to stdout
    command: echo "hello"
    register: hello
  - debug: msg="{{ hello.stdout }}"
  - debug: msg="{{ hello.stderr }}"